version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: devops-converter-backend:latest
    container_name: devops-backend
    environment:
      - APP_ENV=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    ports:
      - "8081:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: devops-converter-frontend:latest
    container_name: devops-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge
