version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: devops-converter-backend:latest
    container_name: devops-backend
    environment:
      - APP_ENV=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    restart: always
    networks:
      - default
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      # TLS router for API
      - "traefik.http.routers.devops-backend.rule=Host(`devops.enokdev.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.devops-backend.entrypoints=websecure"
      - "traefik.http.routers.devops-backend.tls.certresolver=myresolver"
      - "traefik.http.services.devops-backend.loadbalancer.server.port=8080"
      # HTTP router for ACME challenge and redirect to HTTPS
      - "traefik.http.routers.devops-backend-http.rule=Host(`devops.enokdev.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.devops-backend-http.entrypoints=web"
      - "traefik.http.routers.devops-backend-http.middlewares=devops-backend-redirect"
      - "traefik.http.middlewares.devops-backend-redirect.redirectscheme.scheme=https"
    healthcheck:
      test: ["CMD", "/devops-converter", "--health-check"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: devops-converter-frontend:latest
    container_name: devops-frontend
    depends_on:
      - backend
    restart: always
    networks:
      - default
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      # TLS router for frontend
      - "traefik.http.routers.devops-frontend.rule=Host(`devops.enokdev.com`)"
      - "traefik.http.routers.devops-frontend.entrypoints=websecure"
      - "traefik.http.routers.devops-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.devops-frontend.loadbalancer.server.port=80"
      # HTTP router for redirect to HTTPS
      - "traefik.http.routers.devops-frontend-http.rule=Host(`devops.enokdev.com`)"
      - "traefik.http.routers.devops-frontend-http.entrypoints=web"
      - "traefik.http.routers.devops-frontend-http.middlewares=devops-frontend-redirect"
      - "traefik.http.middlewares.devops-frontend-redirect.redirectscheme.scheme=https"

networks:
  default:
    driver: bridge
  web:
    external: true
